package me.d4rk.economiamod;

public class Utils {

    public enum ResultType {NONE, SUCCESS, NOMONEY, SAMEPLAYER, NOSPACE, NOSELLERACCOUNT, NOBUYERACCOUNT, NOTOWNER, QNTIVALID, NOITEM, INVALIDUUID}

}
